#!/bin/sh
. /etc/kerbynet.conf
. $SCRIPTS/net.inc

iptables -mndpi --help |grep -A1000 "ndpi match options:" |grep -v "ndpi match options:" |awk -F" protocol packets." '{print $1}' | awk -F" Match for " '{gsub("_"," ",$2); printf "%s!!%s\n",$2,substr($1,3)'}|sort|awk -F"!!" '{printf "PROTOCOL[\"%s\"]=\"%s\";\n",$2,$1}'

